version: "3.8"

services:
    db:
        image: mysql:8.0
        container_name: mysql_db_8.0
        environment:
            MYSQL_ROOT_PASSWORD: your_root_password
            MYSQL_DATABASE: wordpress_db
            MYSQL_USER: wordpress_user
            MYSQL_PASSWORD: your_password
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
    app:
        image: custom_laravel_nginx
        build:
            target: app
            context: .
            dockerfile: Dockerfile
        restart: always
        container_name: laravel_container_nginx
        env_file:
            - .env
        ports:
            - "8001:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

volumes:
    db_data:
