version: "3.8"

services:
    db:
        image: mysql:8.0
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: your_root_password
            MYSQL_DATABASE: wordpress_db
            MYSQL_USER: wordpress_user
            MYSQL_PASSWORD: your_password
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: custom_laravel_nginx
        restart: always
        container_name: laravel_app
        env_file:
            - .env
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

volumes:
    db_data:
